package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallUserTree;
import org.linlinjava.litemall.db.domain.LitemallUserTreeExample;

public interface LitemallUserTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    long countByExample(LitemallUserTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallUserTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    int insert(LitemallUserTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    int insertSelective(LitemallUserTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    LitemallUserTree selectOneByExample(LitemallUserTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    LitemallUserTree selectOneByExampleSelective(@Param("example") LitemallUserTreeExample example, @Param("selective") LitemallUserTree.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    List<LitemallUserTree> selectByExampleSelective(@Param("example") LitemallUserTreeExample example, @Param("selective") LitemallUserTree.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    List<LitemallUserTree> selectByExample(LitemallUserTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    LitemallUserTree selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallUserTree.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    LitemallUserTree selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    LitemallUserTree selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallUserTree record, @Param("example") LitemallUserTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallUserTree record, @Param("example") LitemallUserTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallUserTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallUserTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallUserTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_tree
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}